### ISSUE TITLE
"How to use this template" looses .github directory

### ISSUE THREAD

**Issue by mithro** [google/new-project#15]
The instructions under the ["How to use this template"](https://github.com/google/new-project#how-to-use-this-template) say;
``` shell
git clone https://github.com/google/new-project
mkdir my-new-thing
cd my-new-thing
git init
cp -r ../new-project/* .
git add *
git commit -a -m 'Boilerplate for new Google open source project'
```

However the template now has a `.github` directory which includes stuff. The `cp -r` will not copy across this directory.

I think you need;
```
cp -r ../new-project/* ../new-project/.github .
```

I wasn't sure if there was a better way to copy "`.`" files from the template while still skipping the `.git` directory?

**Comment by willnorris** [comment]
good call, thanks!
