### ISSUE TITLE
Mark repo as template

### ISSUE THREAD

**Issue by gleich** [google/new-project#23]
## Expected Behavior

Repository marked as a template repo so you can use it right within GitHub. See: 

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

## Actual Behavior

You need to clone it and it is just a normal git repo.

## Steps to Reproduce the Problem

N/A

## Specifications

- Version: N/A
- Platform: GitHub

**Comment by kyleabenson** [comment]
@rspier Could we get this marked as a template? It would make the creation of codespaces significantly easier.

**Comment by rspier** [comment]
Done.
